### ISSUE TITLE
Not autosaving replays

### ISSUE THREAD

**Issue by makloster** [Maxinova/COH3-Replay-Viewer#1]
Hi! The COH3 Replay Viewer is not autosaving replays, maybe I missed some step?

I followed the "Installation" section instructions and ran the executable. Should I also install the Python requirements and/or run the script?

**Comment by Riebeck-one** [comment]
Hi !

It seems you're the first to vive feedback to my app, thanks for that.

Are you running the exe file I provide ? Is the "start acquisition'" square box ticked when you're playing ? If so, it should automatically save your replays at the end of each match.
-- 
Envoyé de mon p≡p pour Android.

**Comment by makloster** [comment]
A pleasure :)

I'm using the exe. Once in the app's window, I select a replay and everything works just fine. When I exit the game, the "start acquisition" unticks, maybe I tried to play after that and that's why it didn't save? I'll check it.

I guess the app has to be running in order to autosave replays, right?

Thanks!
